import NavbarBottom from "./elements/navbarBottom";
import NavbarTop from "./elements/navbarTop";
import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="bg-slate-900 text-slate-200 scroll-smooth  ">
      <body className={inter.className}>
        <NavbarTop />
        {children}
        <NavbarBottom />
      </body>
    </html>
  );
}
